name: Shell Commands 

on: [pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps: 
      - name: echo a string
        run: echo "Hello World"
        timeout-minutes: 0
      - name: multiline script
        continue-on-error: true 
        run: |
           node -v 
           npm -v
      - name: python Command 
        run: |
          import platform 
          print
          (platform.processor())
        shell: python
  run-windwos-commands:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory PowerShell
        run: Get-Location 
      - name: Directory Bash 
        run: pwd 
        shell: bash 